# Generated by Django 4.0.5 on 2022-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='image')),
                ('text', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('pirice', models.PositiveIntegerField(default=100, verbose_name='UZS')),
                ('pirice_usd', models.PositiveIntegerField(default=100, verbose_name='USD')),
                ('leave', models.DateField(blank=True, null=True)),
                ('bakc_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
    ]
